default: &DEFAULT

  #General
  # For computing compression
  n_params_baseline: None
  verbose: True
  arch: 'tfno3d'

  #Distributed computing
  distributed:
    use_distributed: False
    wireup_info: 'mpi'
    wireup_store: 'tcp'
    model_parallel_size: 2
    seed: 666

  # FNO related
  tfno3d:
    data_channels: 1
    out_channels: 1
    n_modes_height: 16 #64
    n_modes_width: 16 #64
    n_modes_depth: 4 #8
    hidden_channels: 8 #16
    lifting_channels: 128
    projection_channels: 128
    n_layers: 4
    domain_padding: None #0.078125
    domain_padding_mode: 'one-sided' #symmetric
    fft_norm: 'forward'
    norm: 'group_norm'
    skip: 'linear'
    implementation: 'factorized'
    separable: 0
    preactivation: 0
    
    use_mlp: 1
    mlp:
        expansion: 0.5
        dropout: 0

    factorization: None
    rank: 1.0
    fixed_rank_modes: None
    dropout: 0.0
    tensor_lasso_penalty: 0.0
    joint_factorization: False
    fno_block_precision: 'full' # or 'half', 'mixed'
    stabilizer: None # or 'tanh'

  # Optimizer
  opt:
    n_epochs: 100
    learning_rate: 5e-3
    training_loss: 'h1'
    weight_decay: 1e-4
    amp_autocast: False

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 5 # For ReduceLROnPlateau only
    scheduler: 'StepLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 60
    gamma: 0.5

  # Dataset related
  data:
    batch_size: 32
    data_path: /d0/magnetograms/hmi/preprocessed/hmi_stacks_2021_2022_96m_full.zarr
    train_resolution: 2048
    test_resolutions: [2048]
    test_batch_sizes: [32]
    crop_size: 128
    random_crop: True
    train_months: [1]
    test_months: [3]
    cadence: 96
    cadence_epsilon: 5
    x_seq_length: 16
    y_seq_length: 16 

  # Patching
  patching:
    levels: 0
    padding: 0
    stitching: False

  # Weights and biases
  wandb:
    log: True
    name: None # If None, config will be used but you can override it here
    group: '' 
    project: "hmi_fno"
    entity: idea-lab # put your username here
    sweep: False
    log_output: True
    log_test_interval: 1
